<?xml version="1.0" encoding="UTF-8"?>
<!-- Encontrados errores:
  1- El último producto contiene dos elementos que se han dividido en dos productos
  -->
<!DOCTYPE productes
  [
  <!ELEMENT productes (producte*)>
  <!ELEMENT producte (ratoli | teclat | monitor)>
  <!ATTLIST ratoli codi ID #REQUIRED>
  <!ATTLIST teclat codi ID #REQUIRED>
  <!ATTLIST monitor codi ID #REQUIRED>
  <!ELEMENT ratoli (#PCDATA)>
  <!ELEMENT teclat (#PCDATA)>
  <!ELEMENT monitor (#PCDATA)>
  ]>
<productes>

    <producte>
        <ratoli codi="r01"> sense fil space </ratoli>
    </producte>
    
    <producte>
        <teclat codi= "t03">Teclat de colors </teclat>
    </producte>
    
    <producte>
        <teclat codi= "t04">Teclat de colors </teclat>
    </producte>
    
    <producte>
      <monitor codi="m100">Tàctil</monitor>
    </producte>
    
 </productes>