=== ToniGar20/DAW/markup-languages/bloc4-xml/xml-xsd-validation/ex2-persones.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
“data_naixement” es posa com a tipus date i es canvien es valors al XML per a que es pugui validar
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="persones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="llinatge" type="xs:string"/>
              <xs:element name="edat" type="xs:integer"/>
              <xs:element name="data_naixement" type="xs:date"/>
             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ToniGar20/DAW/markup-languages/bloc4-xml/xml-xsd-validation-4/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
1. Editades les etiquetes de tancament de “data_naixement”
2. Canviat el format de la data a YYYY-MM-DD
-->

<persones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ex2-persones.xsd">

   <persona>
      <llinatge>Ruíz</llinatge>
      <edat>36</edat>
      <data_naixement>1985-10-03</data_naixement>
   </persona>
   
   <persona>
      <llinatge>Pons</llinatge>
      <edat>45</edat>
      <data_naixement>1979-10-03</data_naixement>
   </persona>
   
</persones>
