=== ToniGar20/DAW/markup-languages/bloc4-xml/xml-xsd-validation/film.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pelicula"> <!-- Element arrel -->
    <xs:complexType>
      <xs:sequence>
        <xs:element name="director" type="xs:string"/> <!-- Primer subelement -->
        <xs:element name="repartiment"> <!-- Segon subelement -->
          <xs:complexType> <!-- El segon subelement té fills però son només d'un tipus -->
            <xs:sequence>
              <xs:element name="interpret" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
              <!-- He definit que els intèrprets es puguin repetir totes les vegades necessàries -->
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="titol" type="xs:string"/> <!-- 1er Atribut del element arrel-->
      <xs:attribute name="minuts" type="xs:integer"/> <!-- 2n Atribut del element arrel -->
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ToniGar20/DAW/markup-languages/bloc4-xml/xml-xsd-validation/ex9.xml
<?xml version="1.0"?>
<pelicula titol="Brazil" minuts="142"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="film.xsd">
    <director>Terry Gilliam</director>
    <repartiment>
       <interpret>Jonathan Pryce</interpret>
       <interpret>Robert De Niro</interpret>
       <interpret>Kim Greist</interpret>
       <interpret>Michael Palin</interpret>
       <interpret>Ian Holm</interpret>
       <interpret>Bob Hoskins</interpret>
    </repartiment>
</pelicula>
